name: Broken Link Checker

on:
  workflow_run:
    workflows: ["Deploy Jekyll site to Pages"]
    types:
      - completed

jobs:
  linkchecker:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Wait for deployment
        run: sleep 30
      
      - name: Check for broken links
        uses: celinekurpershoek/link-checker@v1.0.2
        with:
          url: "https://www.powerplatformtip.com"
          honorRobotExclusions: false
          ignorePatterns: "github,google,linkedin"
          recursiveLinks: true
