name: Lighthouse SEO & Performance Audit
on:
  pull_request:
    branches: [ main ]
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Jekyll site
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli
      - name: Run Lighthouse CI
        run: |
          npx lhci autorun --collect.url=http://localhost:4000 --collect.staticDistDir=_site --upload.target=temporary-public-storage || true
