name: Security Scan

on:
  workflow_run:
    workflows: ["Deploy Jekyll site to Pages"]
    types:
      - completed
  schedule:
    - cron: '0 2 * * 0'  # Sonntags um 2 Uhr

jobs:
  security-audit:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'schedule' }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'repo'
          scan-ref: '.'
      
      - name: Check for exposed secrets
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: main
          head: HEAD
