name: Sitemap Validation

on:
  workflow_run:
    workflows: ["Deploy Jekyll site to Pages"]
    types:
      - completed

jobs:
  validate-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      
      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils
      
      - name: Build Jekyll site
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      
      - name: Check if sitemap.xml exists
        run: |
          if [ ! -f "_site/sitemap.xml" ]; then
            echo "❌ sitemap.xml not found in _site/"
            exit 1
          else
            echo "✅ sitemap.xml found"
          fi
      
      - name: Validate sitemap.xml
        run: |
          xmllint --noout _site/sitemap.xml
          echo "✅ sitemap.xml is valid XML"
      
      - name: Show sitemap content (first 20 lines)
        run: |
          echo "Sitemap content preview:"
          head -20 _site/sitemap.xml
