name: Sitemap Validation
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Jekyll site
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Rebuild sitemap.xml
        run: |
          bundle exec jekyll build
      - name: Validate sitemap.xml
        run: |
          xmllint --noout _site/sitemap.xml
