name: Spelling and Grammar Linting

on:
  workflow_run:
    workflows: ["Deploy Jekyll site to Pages"]
    types:
      - completed

jobs:
  spelling:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Node.js (für markdownlint)
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install Vale using package manager
        run: |
          wget -qO- https://github.com/errata-ai/vale/releases/latest/download/vale_Linux_x86_64.tar.gz | tar -xz -C /tmp
          sudo mv /tmp/vale /usr/local/bin/vale
          vale --version
      
      - name: Create basic Vale config
        run: |
          cat > .vale.ini << 'EOF'
          StylesPath = styles
          MinAlertLevel = suggestion
          [*.md]
          BasedOnStyles = Vale
          EOF
          mkdir -p styles
      
      - name: Run Vale on Markdown files
        run: |
          vale . || true
      
      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli
      
      - name: Run markdownlint
        run: |
          markdownlint "**/*.md" --ignore node_modules || true
