name: Spelling and Grammar Linting

on:
  workflow_run:
    workflows: ["Deploy Jekyll site to Pages"]
    types:
      - completed

jobs:
  spelling:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Create minimal Vale config
        run: |
          cat > .vale.ini << 'EOF'
          StylesPath = styles
          MinAlertLevel = suggestion
          Packages = Microsoft
          
          [*.md]
          BasedOnStyles = Vale
          EOF
          mkdir -p styles
      
      - name: Run Vale spell check
        uses: simbo/vale-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: '.'
          fail_on_error: false
      
      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli
      
      - name: Run markdownlint
        run: |
          markdownlint "**/*.md" --ignore node_modules --ignore _site || true
