name: Spelling and Grammar Linting

on:
  workflow_run:
    workflows: ["Deploy Jekyll site to Pages"]
    types:
      - completed

jobs:
  spelling:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install markdownlint-cli only
        run: npm install -g markdownlint-cli
      
      - name: Run markdownlint
        run: |
          markdownlint "**/*.md" --ignore node_modules --ignore _site || true
      
      - name: Check for common German/English typos
        run: |
          echo "Checking for common typos..."
          grep -r "das das\|der der\|die die" _posts/ || echo "✅ No duplicate German articles found"
          grep -r "PowerPlatfrom\|PowerPlattform" _posts/ || echo "✅ No PowerPlatform typos found"
          grep -r "recieve\|seperate\|definately" _posts/ || echo "✅ No common English typos found"
          echo "✅ Basic typo check completed"
