name: Uptime Monitor

on:
  schedule:
    - cron: '*/30 * * * *'  # Alle 30 Minuten

jobs:
  uptime-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check website availability
        uses: gr2m/uptime-action@v1
        with:
          url: "https://www.powerplatformtip.com"
          expected_status: "200,201,301,302"
      
      - name: Notify on failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          text: "🚨 PowerPlatform Tip Website ist nicht erreichbar!"